### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/website#14]
Landing page should explain what is Python workshops to all new comers. The goal is to explain new visitors what we do and if those who are interested show how to join our team.

Currently landing page is occupied by projects. Projects should be moved to separate menu item.

Things that should be present on landing page:

1. What is Python workshops.

2. Logo.

3. Who can attend? Should be mentioned that everyone can attend and all events are free.

4. List (or one event) of upcoming events, with information where and when.

5. Video with short introduction about Python workshops.

**Comment by niekas** [comment]
Different pages should be shown for anonymous and for logged in users.

**Comment by iakovleva** [comment]
Could we close  this issue for now? 
@sirex will you deploy what we have at the moment?

**Comment by sirex** [comment]
@iakovleva just deployed and I'm closing this issue.
