### ISSUE TITLE
Event page

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/website#22]
Create event page accessible from following URL: `/events/<year>/<month>/<day>/<event title slug>/`.

Event page should display event title, date, venue with map and description.

Depends on: #21.

**Comment by vomaxHELLnO** [comment]
Should I also create event list page and menu item "Events"?

**Comment by sirex** [comment]
No. Currently there will be no list of events, at least not in this sprint. The only list of events will be in title page, described in #27.

You task is just event page.
