### ISSUE TITLE
Model graph is not working

### ISSUE THREAD

**Issue by Euphorbium** [python-dirbtuves/website#39]
When I try `bin/django graph_models -g -a -o graph.png` I get `CommandError: Neither pygraphviz nor pydot could be found to generate the image` But I have pygraphviz and graphviz installed and I can import pygraphviz in both python2 and pyhton3. Is this because the project uses some kind of separate python with all of the dependancies in an egg? How and where should the pygraphviz be installed for this command to work?

**Comment by sirex** [comment]
You can install it with `bin/pip install ..` for your own usage. If you want this to be available for everyone else, add it to `setup.py` or `config/base.cfg`.

By the way, why you need model graph if we have only two models?

**Comment by Euphorbium** [comment]
Because a picture is worth a thousand words. This was one of my favourite features of web2py. If anybody else is interested this is what I am talking about. ![graph of the current models](http://i.imgur.com/6b5JVdJ.png)
