### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/website#4]
Create static about page and menu item that points to this about page.

About page should have a map (OpenStreetMap based) and description what we do, when we meet and where.

**Comment by niekas** [comment]
[Universal declaration of human rights](http://www.un.org/en/documents/udhr/) states, that " No one shall be subjected to arbitrary interference with his privacy, (...) Everyone has the right to the protection of the law against such interference or attacks."

**Comment by sirex** [comment]
I think, this task is done and should be closed?

**Comment by niekas** [comment]
Replace Summer Python Workshop description with a list of Top level ```Event``` instances. Show title and abbreviated description for each top level ```Event``` instance (which does not have parent event). Abbreviation can be done using [truncatechars](https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#truncatechars) filter. You should create Event instance for Summer Python Workshop and move the description from about.html page to this instance.
